

playlist = {
    "Multo": {
        "file": "multo.mp3",
        "lyrics": [
            (0,  "Humingang malalim, pumikit na muna"),
            (6,  "At baka-sakaling namamalikmata lang"),
            (12, "Ba't nababahala? 'Di ba't ako'y mag-isa?"),
            (18, "'Kala ko'y payapa, boses mo'y tumatawag pa"),
            (24, "Binaon naman na ang lahat"),
            (30, "Tinakpan naman na 'king sugat"),
            (36, "Ngunit ba't ba andito pa rin?"),
            (42, "Hirap na 'kong intindihin"),
            (48, "Tanging panalangin, lubayan na sana"),
            (54, "Dahil sa bawat tingin, mukha mo'y nakikita"),
            (60, "Kahit sa’n man mapunta ay anino mo'y kumakapit sa 'king kamay"),
            (66, "Ako ay dahan-dahang nililibing nang buhay pa"),
            (72, "Hindi na makalaya"),
            (78, "Dinadalaw mo 'ko bawat gabi"),
            (84, "Wala mang nakikita"),
            (90, "Haplos mo'y ramdam pa rin sa dilim"),
            (96, "Hindi na nananaginip"),
            (102,"Hindi na ma-makagising"),
            (108,"Pasindi na ng ilaw"),
            (114,"Minumulto na 'ko ng damdamin ko"),
            (120,"Ng damdamin ko"),
            (126,"Hindi mo ba ako lilisanin?"),
            (132,"Hindi pa ba sapat pagpapahirap sa 'kin?"),
            (138,"Hindi na ba ma-mamamayapa?"),
            (144,"Hindi na ba ma-mamamayapa?"),
            (150,"Hindi na makalaya"),
            (156,"Dinadalaw mo 'ko bawat gabi"),
            (162,"Wala mang nakikita"),
            (168,"Haplos mo'y ramdam pa rin sa dilim"),
            (174,"Hindi na nananaginip"),
            (180,"Hindi na ma-makagising"),
            (186,"Pasindi na ng ilaw"),
            (192,"Minumulto na 'ko ng damdamin ko"),
            (198,"Ng damdamin ko"),
            (204,"Hindi mo ba ako lilisanin?"),
            (210,"Hindi pa ba sapat pagpapahirap sa 'kin?"),
            (216,"Hindi na ba ma-mamamayapa?"),
            (222,"Hindi na ba ma-mamamayapa?"),
        ],
    },
    "Blue by Kai": {
        "file": "blue_by_kai.mp3",
        "lyrics": [
            (0,  "Your morning eyes.... I could stare like watching stars.."),
            (6,  "I could walk you by, and I'll tell without a thought"),
            (12, "You'd be mine, would you mind if I took your hand tonight?"),
            (18, "Know you're all that I want this life"),
            (24, "I'll imagine we fell in love"),
            (30, "I'll nap under moonlight skies with you"),
            (36, "I think I'll picture us, you with the waves"),
            (42, "The ocean's colors on your face"),
            (48, "I'll leave my heart with your air"),
            (54, "So let me fly with you"),
            (60, "Will you be forever with me?"),
            (66, "My love will always stay by you"),
            (72, "I'll keep it safe, so don't you worry a thing"),
            (78, "I'll tell you I love you more"),
            (84, "It's stuck with you forever, so promise you won't let it go"),
            (90, "I'll trust the universe will always bring me to you"),
            (96, "I'll imagine we fell in love"),
            (102,"I'll nap under moonlight skies with you"),
            (108,"I think I'll picture us, you with the waves"),
            (114,"The ocean's colors on your face"),
            (120,"I'll leave my heart with your air"),
            (126,"So let me fly with you"),
            (132,"Will you be forever with me?"),
        ],
    },
}
